# Generated by Django 3.1.2 on 2020-10-20 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201020_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='occupationn',
            new_name='occupation',
        ),
    ]
