# Generated by Django 3.1.2 on 2020-10-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201020_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='blogs',
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
