# Generated by Django 3.1.2 on 2020-11-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='tipe_berita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publishing', to='berita.tipeberita'),
        ),
    ]
